stages:
  - read
  - resize
  - save
  - deduplication

filter_func:
  function: true
  args:
    min_size: [224, 224]

read:
  args:
    - filter_func
  outputs:
    - images
    - imagenames

resize:
  args:
    dst_size: [224, 224]
  inputs:
    - images
  outputs:
    - resized_images

save:
  inputs:
    - resized_images
    - imagenames
  outputs:
    - empty

deduplication:
  nullsrc:
    data_dir
  args:
    batch_size: 64
  inputs:
    - resized_images
    - imagenames
  outputs:
